### ISSUE TITLE
Defining the search-window criteria for different tasks

### ISSUE THREAD

**Issue by Demolaw** [kenaniah/swords-and-potions-2-bot#5]
as i have observed while running the bot he tries to search the whole window for every given task, is it possible to define a specific screenpart for a given routine?

example: while he search for employee, i came up with the idea to use these space for them
![choosed space](https://cloud.githubusercontent.com/assets/9409016/4787768/68eacba6-5db0-11e4-91e5-44eb21d974e6.png)
it works, atleast by my test run.
my question is, is it possible and if, where can i define the x,y range for an given task.
that way it's maybe can be fastened, if you won't know, you are welcome then i maybe get it figured out aswell on my own  ^^

PS: how does the lable system works on github :grey_question:  because it's no issue more a request /idea

**Comment by kenaniah** [comment]
Unfortunately the Automa API currently does not support ranges. This is something I have been wanting to do for some time, but Automa was chosen as the pragmatic tool for the job given it's relatively simple API.

An alternative that does make ranged searches possible would be to use OpenCV, but one could argue that it would not be a viable solution as you would need to implement your own image matching logic on a low level. At that point, you might as well write something in C. 

Concerning the employee searching, I deliberately did not the employee portraits because they do not represent unique state. You'll notice that once an employee is commanded to build something, the image remains unchanged until they gather resources and start crafting. While in the gathering phase, a sprite of the item to be crafted is added to the top-left outside of the portrait, which is impossible for Automa to detect. In short, there's no way to truly tell if the employee is actually free or not just by looking at their portraits.
